# Young People Survey: Learning The Preferences of Our Peers

#### *Youth is wasted on the young.  -- George Bernard Shaw*

An analysis using the Young People Survey data found on Kaggle: https://www.kaggle.com/miroslavsabo/young-people-survey

What does it mean to be young? We're about to find out. 

About the data: 
* This is a dataset composed of survey responses from a statistics class at a Slovakian university in 2013.
* The data file (responses.csv) consists of 1010 rows and 150 columns (139 integer and 11 categorical).
* All participants were of Slovakian nationality, aged between 15-30.
* The variables can be split into the following groups:
  * Music preferences (19 items)
  * Movie preferences (12 items)
  * Hobbies & interests (32 items)
  * Phobias (10 items)
  * Health habits (3 items)
  * Personality traits, views on life, & opinions (57 items)
  * Spending habits (7 items)
  * Demographics (10 items)

## Table of Contents

1. [Data Cleaning](#cln)
* [Removing NaNs](#nan)
2. [EDA](#eda)

In [1]:
# importing packages
%matplotlib inline
import pandas as pd
import copy
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier

In [3]:
# importing the data
young = pd.read_csv('responses.csv')
young.head(5)

,Music,Slow songs or fast songs,Dance,Folk,Country,Classical music,Musical,Pop,Rock,Metal or Hardrock,...,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,5.0,3.0,2.0,1.0,2.0,2.0,1.0,5.0,5.0,1.0,...,20.0,163.0,48.0,1.0,female,right handed,college/bachelor degree,no,village,block of flats
1,4.0,4.0,2.0,1.0,1.0,1.0,2.0,3.0,5.0,4.0,...,19.0,163.0,58.0,2.0,female,right handed,college/bachelor degree,no,city,block of flats
2,5.0,5.0,2.0,2.0,3.0,4.0,5.0,3.0,5.0,3.0,...,20.0,176.0,67.0,2.0,female,right handed,secondary school,no,city,block of flats
3,5.0,3.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,...,22.0,172.0,59.0,1.0,female,right handed,college/bachelor degree,yes,city,house/bungalow
4,5.0,3.0,4.0,3.0,2.0,4.0,3.0,5.0,3.0,1.0,...,20.0,170.0,59.0,1.0,female,right handed,secondary school,no,village,house/bungalow

In [6]:
# checking out the column headers and data types
young.dtypes

Music                         float64
Slow songs or fast songs      float64
Dance                         float64
Folk                          float64
Country                       float64
Classical music               float64
Musical                       float64
Pop                           float64
Rock                          float64
Metal or Hardrock             float64
Punk                          float64
Hiphop, Rap                   float64
Reggae, Ska                   float64
Swing, Jazz                   float64
Rock n roll                   float64
Alternative                   float64
Latino                        float64
Techno, Trance                float64
Opera                         float64
Movies                        float64
Horror                        float64
Thriller                      float64
Comedy                        float64
Romantic                      float64
Sci-fi                        float64
War                           float64
Fantasy/Fairy tales           float64
Animated                      float64
Documentary                   float64
Western                       float64
                               ...
Public speaking               float64
Unpopularity                  float64
Life struggles                float64
Happiness in life             float64
Energy levels                 float64
Small - big dogs              float64
Personality                   float64
Finding lost valuables        float64
Getting up                    float64
Interests or hobbies          float64
Parents' advice               float64
Questionnaires or polls       float64
Internet usage                 object
Finances                      float64
Shopping centres              float64
Branded clothing              float64
Entertainment spending        float64
Spending on looks             float64
Spending on gadgets             int64
Spending on healthy eating    float64
Age                           float64
Height                        float64
Weight                        float64
Number of siblings            float64
Gender                         object
Left - right handed            object
Education                      object
Only child                     object
Village - town                 object
House - block of flats         object
Length: 150, dtype: object

In [ ]:
young = young.drop([0])
young.columns = ['names']